plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
}

def nameSpace = "com.common.nothing.jmdns"
def projectName = "jmdns"
def versionAAR = "1.0.0"
// 定义一个辅助方法来添加依赖节点
def addDependencyToNode(def parentNode, def dep, def scope = null) {
    def dependencyNode = parentNode.appendNode('dependency')
    dependencyNode.appendNode('groupId', dep.group)
    dependencyNode.appendNode('artifactId', dep.name)
    dependencyNode.appendNode('version', dep.version)
    if (scope != null) {
        dependencyNode.appendNode('scope', scope)
    }
}
afterEvaluate {
    publishing {
        publications {
            maven2(MavenPublication) {
                groupId = nameSpace
                artifactId = projectName
                version = versionAAR
                // 将 from 方法移动到 MavenPublication 配置块内
                from components.release
                // 手动添加依赖信息
                pom {
                    packaging 'aar'
                    withXml {
                        def dependenciesNode = asNode().appendNode('dependencies')
                        // 处理 api 依赖
                        configurations.api.allDependencies.each { dep ->
                            if (dep.group != null && dep.name != null && dep.version != null) {
                                addDependencyToNode(dependenciesNode, dep, null)
                            }
                        }
                    }
                }
            }

        }
        repositories {
            maven {
                url = 'https://packages.aliyun.com/maven/repository/2236604-release-GJXgei/'
                credentials {
                    username = '5f963d8b18c17e7748e21932'
                    password = 'GrkJhRnBbJ_S'
                }
            }
            maven {
                url = 'https://packages.aliyun.com/maven/repository/2236604-snapshot-ykFnBh/'
                credentials {
                    username = '5f963d8b18c17e7748e21932'
                    password = 'GrkJhRnBbJ_S'
                }
            }
        }
    }
}

android {
    compileSdk configCompileSDK
    namespace nameSpace
    defaultConfig {
        minSdk configMinSDK
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    compileOptions {
        sourceCompatibility javaSDK
        targetCompatibility javaSDK
    }
    buildFeatures {}
    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

dependencies {
    implementation project(':common')

//  这个版本版衣的时候会提D8 导致无法编译  implementation 'dnsjava:dnsjava:3.6.3'
//    implementation 'dnsjava:dnsjava:3.5.3'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'

}
