plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
}

def nameSpace = "com.common.nothing.jmdns"
def projectName = "jmdns"
def versionAAR = "1.0.0"

afterEvaluate {
    publishing {
        publications {
            maven2(MavenPublication) {
                groupId = nameSpace
                artifactId = projectName
                version = versionAAR
            }
        }
        repositories {
            maven {
                url = 'https://packages.aliyun.com/maven/repository/2236604-release-GJXgei/'
                credentials {
                    username = '5f963d8b18c17e7748e21932'
                    password = 'GrkJhRnBbJ_S'
                }
            }
            maven {
                url = 'https://packages.aliyun.com/maven/repository/2236604-snapshot-ykFnBh/'
                credentials {
                    username = '5f963d8b18c17e7748e21932'
                    password = 'GrkJhRnBbJ_S'
                }
            }
        }
    }
}

android {
    compileSdk configCompileSDK
    namespace nameSpace
    defaultConfig {
        minSdk configMinSDK
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    compileOptions {
        sourceCompatibility javaSDK
        targetCompatibility javaSDK
    }
    buildFeatures {}
    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

dependencies {
    implementation project(':common')

    implementation 'dnsjava:dnsjava:3.6.3'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'

}
